text = "AAAAAACAGACCTTACCATTGCCTCGAAGTATCTATCGATCGATCATTTCTTTCAGACCTCAGACCCCTATAGAGTTTTATGGTCAGGATGCTACTGAAAGTACTGTACTGAAATTACTCACCTGAGGCGCCCGAGGCGCGAGGGGCTCTGCGAGGGGCCACATTGAGTTACGCATGTGTCCACCGTACGCCGAACTACAGCTGAGGCCAACACGGCTGACGTTGATATGGGGTGGGCGGTGAGTAACTAGGTTGGTTCATAGGGTTCATAATACAAATGCCTTGCCCCTGGCATGCCTTCGTGTGTCCGGAAGGGGCGGGGAGACTTATAGTAGAGCTAGAGCGGCGGGGGGAGTTACAAAAGTTTAGCCCACCATCCTTTACCGGGGCCAACTCTACCCAATTAGCTTTGGCGACTGAATTTCACGCGATATGCAAAAGAGCAGTATGAACAGGTATTAGGGGTCCTATATACCTTCTTCGATGTTAGCGACGACTTTACCTTAGCGTTCTAGCGGTTTCAACGCTCTGTGTCGGGACTACGCCTTAGTGGTGTCGTCGATGTAGGGTAGACTCCTACCTTGATCTCACAGTGGCACCCCAGCCCAGCAAGCCCCCCAGCAAAGGTCTCAGCGCAGGTCTCAGCTCTCAGCCCAGGGGGCGCGCGTGTTCTGTTCGTATTCTATAAAGTCAAGCGAAGGGACCCTGACTTTCTTGAGAGCTACACTGCGGCCCTCTATCCGGCGCTATTGGTGTCTTGACCCCTTGTAGGCTCGTTTTATAGAGCGGGAGATGTGTCGCTGTAATGGGGTAGTGGGATTAAAGACTCAATAGCCCAGCGGTGCGATCCTTTAAAGGACTATTCAAAAAGGTAAAAACACATCTGATACCCCACAAAGGAGTACAGCGTATCCAATTCATTAATAACGCGTAGTCATAGATATTCTCTCCACTCCAGATCTCCAGATATCCAGATGGTTGCTTGCTCAACCAATTCTGAGCGCGCTGCCATGGACACACTATCTAAGTCGCTTCTTATAAGAACCATTTAAGACTCATTTAAGGAGAAAATACGCTTTTAGCAACTGATTTTTCGGCGTCGGTCAAGATTCCTATCTACCCACAAGGATCCTCGTCTGCTGCTCCGTTTGCTCCGTCCGCAATACCTTAGTGCCTCAAAGCACGAAAAGGGCAAAAAGGGCCGGGCCGTCAGGTGACCTCCGTCACACCGATTCCAGGGCGCCCATTTATACCCCACTTAGAACCGACAGTCCGCATTTTAGCCGCTGCGACTCCTGTATCAACGGGCCAACGCTACGTCTACGTACTACGTACGTACGTATAACATATGTATGTACCATACATATGTAGTAAAGCCGCGTCCAATCCACTACCAAACCCACGGATCAGTAAGGCACGAAGGTTGTATTCTAAACCTCAGAAGGTAAGGCGATCGGGAGGCGTCACGCACCGGTTCGGGTATCCTACGCTCAACGAAGATGACGTAAATTCACGCTGGTGAAGGGTCCCTAGGGACCCCTGTGTAAGGTACCGAACACAAACGAGGGCCAAAATCGACCGGTATCCTGTAGAGGGTATTTAGCCTACAAGGCATATTCCGCTGTTATCGCGCGGGCCATCTCTTGTGGTATGAGATGCACCGTTGGGTCCTGGGGACCCCCAAAGAGATGAGGTCCTTACCAGGCAGACAATAGAGGGGAATGACAGCGGAATGCAATGCCTCCGAGAAGAAGCGGCGAAGCGAAGCGGCCCCTGCCTGTTCATGCGTTCATGCGTTCATGCGTTCATGCGTTCATGCGTTCGCCACAAGGCCACAAGGCCACAAGGCCACAAGGCCACAAGGCCACAAGGCCACAAGGCCACAAG"
k = 8
L = 26
t = 4     

def findclumps(text, k, L, t):
    patterns = []
    n = len(text)
    for i in range(0, n - L + 1):
        window = text[i: i+L]
        freq_table = {}
        for j in range(0, len(window) - k + 1):
            kmer = window[j: j+k]
            if freq_table.get(kmer):
                freq_table[kmer] = freq_table[kmer] + 1
            else:
                freq_table[kmer] = 1
        
        for kmer, frequency in freq_table.items():
            if frequency >= t:
                patterns.append(kmer)
    patterns = list(dict.fromkeys(freq_table))
    return patterns

print(findclumps(text, k, L, t))
    
        
